# telegram_doudizhu_bot/config.example.py
BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN_HERE"
ADMIN_USER_IDS = [123456789]
REQUIRED_GROUP_ID = 0 # Set to your target group ID, or 0 if no specific group required
DATABASE_NAME = "doudizhu_bot.db"
DEFAULT_LANG = "zh_CN"

BID_TIMEOUT_SECONDS = 60
PLAY_TIMEOUT_SECONDS = 75
JOIN_GAME_TIMEOUT_SECONDS = 300

RATE_LIMIT_CALLS = 5
RATE_LIMIT_PERIOD = 10

DEFAULT_ALLOW_THREE_ONE_PLANE = True
DEFAULT_ALLOW_FOUR_TWO_SINGLE = True
DEFAULT_ALLOW_FOUR_TWO_PAIR = True

LOG_LEVEL = "INFO"
LOG_FILE = "bot.log"

AI_PLAYER_COUNT_TO_START_GAME = 1
LEADERBOARD_TOP_N = 10
